# Generated by Django 5.2.15 on 2026-07-04 06:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='telemetry.student')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('client_event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('timestamp', models.DateTimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('level_id', models.CharField(max_length=50)),
                ('construct_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('payload', models.JSONField()),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='telemetry.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_events', to='telemetry.student')),
            ],
        ),
    ]
