# Generated by Django 5.2.15 on 2026-07-05 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0002_campus_student_user_classroom_student_classroom_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(default='default', max_length=50, unique=True)),
                ('a', models.FloatField(default=23.08)),
                ('b', models.FloatField(default=303.0)),
                ('advanced_cutoff', models.IntegerField(default=327)),
                ('proficient_cutoff', models.IntegerField(default=300)),
                ('basic_cutoff', models.IntegerField(default=278)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='parent_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents', to='telemetry.student'),
        ),
    ]
