# Generated by Django 5.2.15 on 2026-07-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0004_campus_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherinvite',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
