# Generated by Django 5.2.15 on 2026-07-14 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0005_alter_teacherinvite_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='parent_students',
            field=models.ManyToManyField(blank=True, related_name='parents', to='telemetry.student'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='premium_slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='parent_student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parents_legacy', to='telemetry.student'),
        ),
    ]
