# Generated by Django 5.2.15 on 2026-07-14 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0006_userprofile_parent_students_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBKTState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcription_p_know', models.FloatField(default=0.2)),
                ('transcription_p_guess', models.FloatField(default=0.25)),
                ('transcription_p_slip', models.FloatField(default=0.1)),
                ('transcription_p_transit', models.FloatField(default=0.15)),
                ('translation_p_know', models.FloatField(default=0.15)),
                ('translation_p_guess', models.FloatField(default=0.2)),
                ('translation_p_slip', models.FloatField(default=0.12)),
                ('translation_p_transit', models.FloatField(default=0.18)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_state', to='telemetry.student')),
            ],
        ),
    ]
