# Generated by Django 5.2.15 on 2026-07-14 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0007_studentbktstate'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['student', 'event_type'], name='telemetry_t_student_d6d4fd_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['session', 'event_type'], name='telemetry_t_session_ed6856_idx'),
        ),
    ]
