# Generated by Django 5.2.15 on 2026-07-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0008_telemetryevent_telemetry_t_student_d6d4fd_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbktstate',
            name='bonding_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='bonding_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='bonding_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='bonding_p_transit',
            field=models.FloatField(default=0.15),
        ),
    ]
