# Generated by Django 5.2.15 on 2026-07-14 06:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0009_studentbktstate_bonding_p_guess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentBKTHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('construct_tag', models.CharField(max_length=100)),
                ('p_know', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bkt_history', to='telemetry.student')),
            ],
        ),
    ]
