# Generated by Django 5.2.15 on 2026-07-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0011_alter_userprofile_role_invoicereceipt'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['timestamp'], name='telemetry_t_timesta_52c0c6_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['construct_tag'], name='telemetry_t_constru_b27c19_idx'),
        ),
        migrations.AddIndex(
            model_name='telemetryevent',
            index=models.Index(fields=['student', 'construct_tag', 'timestamp'], name='telemetry_t_student_4a9f7b_idx'),
        ),
    ]
