# Generated by Django 5.2.15 on 2026-07-14 07:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0012_telemetryevent_telemetry_t_timesta_52c0c6_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LTIPlatform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('issuer', models.CharField(max_length=255, unique=True)),
                ('client_id', models.CharField(max_length=255)),
                ('auth_login_url', models.URLField()),
                ('auth_token_url', models.URLField()),
                ('key_set_url', models.URLField()),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='lti_context_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='lti_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='LTIGradeSyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('level_id', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('status', models.CharField(default='Success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lti_grade_logs', to='telemetry.student')),
            ],
        ),
    ]
