# Generated by Django 5.2.15 on 2026-07-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0014_reportschedule_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbktstate',
            name='mutation_p_guess',
            field=models.FloatField(default=0.25),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='mutation_p_know',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='mutation_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='mutation_p_transit',
            field=models.FloatField(default=0.15),
        ),
    ]
