# Generated by Django 5.2.15 on 2026-07-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0015_studentbktstate_mutation_p_guess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbktstate',
            name='hierarchy_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='hierarchy_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='hierarchy_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='hierarchy_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='homeostasis_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='homeostasis_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='homeostasis_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='homeostasis_p_transit',
            field=models.FloatField(default=0.15),
        ),
    ]
