# Generated by Django 5.2.15 on 2026-07-26 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0019_studentbktstate_biodiversity_p_guess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbktstate',
            name='carbon_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='carbon_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='carbon_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='carbon_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='energy_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='energy_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='energy_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='energy_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='matter_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='matter_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='matter_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='matter_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='stability_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='stability_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='stability_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='stability_p_transit',
            field=models.FloatField(default=0.15),
        ),
    ]
