# Generated by Django 5.2.15 on 2026-07-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0020_studentbktstate_carbon_p_guess_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbktstate',
            name='behavior_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='behavior_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='behavior_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='behavior_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='inheritance_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='inheritance_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='inheritance_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='inheritance_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='statistics_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='statistics_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='statistics_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='statistics_p_transit',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='variation_p_guess',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='variation_p_know',
            field=models.FloatField(default=0.15),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='variation_p_slip',
            field=models.FloatField(default=0.1),
        ),
        migrations.AddField(
            model_name='studentbktstate',
            name='variation_p_transit',
            field=models.FloatField(default=0.15),
        ),
    ]
