# Generated by Django 5.2.15 on 2026-08-19 19:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0024_studentbktstate_conservation_p_guess_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('prompt', models.TextField()),
                ('starter_code', models.TextField(blank=True, null=True)),
                ('test_suite', models.JSONField(help_text='List of test assertions to run in Pyodide.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PythonSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('output', models.TextField(blank=True, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('score', models.IntegerField(default=0)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('test_results', models.JSONField(help_text='Detailed results of each assertion.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='telemetry.pythonassignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='python_submissions', to='telemetry.student')),
            ],
        ),
    ]
