# Generated by Django 5.2.15 on 2026-08-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0025_pythonassignment_pythonsubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonassignment',
            name='module',
            field=models.IntegerField(default=1, help_text='The curriculum module index (1 = Variables, 2 = Selection/Loops, etc.)'),
        ),
    ]
