# Generated by Django 5.2.15 on 2026-08-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0026_pythonassignment_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='python_assessment_max_attempts',
            field=models.IntegerField(default=100),
        ),
    ]
