# Generated by Django 5.2.15 on 2026-08-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0027_classroom_python_assessment_max_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='pythonsubmission',
            name='selected_for_grading',
            field=models.BooleanField(default=False),
        ),
    ]
