# Generated by Django 5.2.15 on 2026-08-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0028_pythonsubmission_selected_for_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='python_extra_attempts',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
