# Generated by Django 5.2.15 on 2026-08-21 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telemetry', '0029_student_python_extra_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='google_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
